default[:ruby_scripts_dir] = '/rubyscripts'
default[:binaries_directory] = '/deployscripts_binaries'
default[:powershell_scripts_dir] = '/PowershellScripts'
default[:websites_directory] = '/websites'
default[:ui_test_directory] = '/ui_tests'